/**
 * Mock data for NBA Dashboard sections that don't have backend APIs yet.
 * Replace with real API calls when backends are available.
 */

// ─── Live Scores ───────────────────────────────────────────────
export const mockLiveScores = [
    {
        id: 1,
        status: 'LIVE',
        quarter: 'Q3',
        clock: '4:23',
        home: { name: 'Lakers', abbr: 'LAL', score: 87, color: '#552583' },
        away: { name: 'Celtics', abbr: 'BOS', score: 91, color: '#007A33' },
    },
    {
        id: 2,
        status: 'LIVE',
        quarter: 'Q2',
        clock: '8:15',
        home: { name: 'Warriors', abbr: 'GSW', score: 54, color: '#1D428A' },
        away: { name: 'Nuggets', abbr: 'DEN', score: 48, color: '#0E2240' },
    },
    {
        id: 3,
        status: 'FINAL',
        quarter: '',
        clock: '',
        home: { name: 'Bucks', abbr: 'MIL', score: 118, color: '#00471B' },
        away: { name: '76ers', abbr: 'PHI', score: 112, color: '#006BB6' },
    },
    {
        id: 4,
        status: 'FINAL',
        quarter: '',
        clock: '',
        home: { name: 'Suns', abbr: 'PHX', score: 105, color: '#1D1160' },
        away: { name: 'Mavericks', abbr: 'DAL', score: 109, color: '#00538C' },
    },
    {
        id: 5,
        status: '7:30 PM',
        quarter: '',
        clock: '',
        home: { name: 'Heat', abbr: 'MIA', score: 0, color: '#98002E' },
        away: { name: 'Knicks', abbr: 'NYK', score: 0, color: '#F58426' },
    },
    {
        id: 6,
        status: '9:00 PM',
        quarter: '',
        clock: '',
        home: { name: 'Clippers', abbr: 'LAC', score: 0, color: '#C8102E' },
        away: { name: 'Thunder', abbr: 'OKC', score: 0, color: '#007AC1' },
    },
];

// ─── News ──────────────────────────────────────────────────────
export const mockNews = [
    {
        id: 1,
        headline: 'Jokic Records Another Triple-Double in Dominant Win',
        summary: 'Nikola Jokic tallied 32 points, 14 rebounds, and 11 assists as the Nuggets cruised to a comfortable victory over the Warriors.',
        source: 'ESPN',
        date: '2 hours ago',
        category: 'Game Recap',
        url: 'https://www.espn.com/nba/',
        thumbnail: 'https://picsum.photos/seed/nba-news-1/800/450',
    },
    {
        id: 2,
        headline: 'Trade Deadline: Key Moves That Could Reshape the Playoffs',
        summary: 'Several contenders made significant moves ahead of the deadline. We break down the winners and losers.',
        source: 'The Athletic',
        date: '5 hours ago',
        category: 'Analysis',
        url: 'https://www.nytimes.com/athletic/nba/',
        thumbnail: 'https://picsum.photos/seed/nba-news-2/800/450',
    },
    {
        id: 3,
        headline: 'Wembanyama Continues Rookie of the Year Campaign',
        summary: 'Victor Wembanyama put up 28 points and 5 blocks, further cementing his case for the top rookie honor.',
        source: 'NBA.com',
        date: '8 hours ago',
        category: 'Player Watch',
        url: 'https://www.nba.com/news',
        thumbnail: 'https://picsum.photos/seed/nba-news-3/800/450',
    },
    {
        id: 4,
        headline: 'Injury Report: Key Players Out for Upcoming Week',
        summary: 'Multiple All-Stars are set to miss games this week due to various injuries. Here\'s the full breakdown.',
        source: 'Bleacher Report',
        date: '1 day ago',
        category: 'Injuries',
        url: 'https://bleacherreport.com/nba',
        thumbnail: 'https://picsum.photos/seed/nba-news-4/800/450',
    },
    {
        id: 5,
        headline: 'MVP Race Heats Up: Statistical Breakdown of Top Candidates',
        summary: 'With the All-Star break behind us, the MVP race is tighter than ever. We analyze the numbers behind the leading candidates.',
        source: 'FiveThirtyEight',
        date: '1 day ago',
        category: 'Analysis',
        url: 'https://abcnews.go.com/538',
        thumbnail: 'https://picsum.photos/seed/nba-news-5/800/450',
    },
    {
        id: 6,
        headline: 'Celtics Extend Win Streak as Brown and Tatum Combine for 61',
        summary: 'Boston keeps momentum in the East with another efficient two-way performance from its star duo.',
        source: 'CBS Sports',
        date: '1 day ago',
        category: 'Game Recap',
        url: 'https://www.cbssports.com/nba/',
        thumbnail: 'https://picsum.photos/seed/nba-news-6/800/450',
    },
    {
        id: 7,
        headline: 'Thunder Defense Ranked No. 1 Over Last 15 Games',
        summary: 'OKC\'s defensive scheme and rim protection have separated them from the rest of the field entering the playoff run.',
        source: 'The Ringer',
        date: '2 days ago',
        category: 'Analysis',
        url: 'https://www.theringer.com/nba',
        thumbnail: 'https://picsum.photos/seed/nba-news-7/800/450',
    },
    {
        id: 8,
        headline: 'Luka and Kyrie Building Late-Season Chemistry in Dallas',
        summary: 'The Mavericks are seeing better late-game execution as both stars share on-ball reps more effectively.',
        source: 'Yahoo Sports',
        date: '2 days ago',
        category: 'Player Watch',
        url: 'https://sports.yahoo.com/nba/',
        thumbnail: 'https://picsum.photos/seed/nba-news-8/800/450',
    },
    {
        id: 9,
        headline: 'Play-In Race Tightens in the West with Four Teams Within One Game',
        summary: 'Every remaining game matters as seeds 7 through 10 continue to shuffle nightly.',
        source: 'NBA.com',
        date: '2 days ago',
        category: 'Analysis',
        url: 'https://www.nba.com/news',
        thumbnail: 'https://picsum.photos/seed/nba-news-9/800/450',
    },
    {
        id: 10,
        headline: 'Clippers Get Key Rotation Piece Back Before Road Trip',
        summary: 'LA receives a timely boost with a wing defender returning just before a critical set of conference games.',
        source: 'Bleacher Report',
        date: '3 days ago',
        category: 'Injuries',
        url: 'https://bleacherreport.com/nba',
        thumbnail: 'https://picsum.photos/seed/nba-news-10/800/450',
    },
    {
        id: 11,
        headline: 'Raptors Surge Behind Barnes\' Two-Way Leap',
        summary: 'Toronto has climbed the standings by pairing better half-court offense with consistent transition defense.',
        source: 'The Athletic',
        date: '3 days ago',
        category: 'Player Watch',
        url: 'https://www.nytimes.com/athletic/nba/',
        thumbnail: 'https://picsum.photos/seed/nba-news-11/800/450',
    },
    {
        id: 12,
        headline: 'Nuggets Bench Unit Quietly Becomes Top-10 Net Rating Group',
        summary: 'Denver\'s second unit has stabilized both scoring and pace, giving Jokic more manageable minutes.',
        source: 'ESPN',
        date: '4 days ago',
        category: 'Analysis',
        url: 'https://www.espn.com/nba/',
        thumbnail: 'https://picsum.photos/seed/nba-news-12/800/450',
    },
];

// ─── Standings ─────────────────────────────────────────────────
export const mockStandings = {
    eastern: [
        { rank: 1, team: 'Boston Celtics', abbr: 'BOS', w: 48, l: 12, pct: '.800', gb: '-', streak: 'W5', last10: '8-2' },
        { rank: 2, team: 'Cleveland Cavaliers', abbr: 'CLE', w: 44, l: 17, pct: '.721', gb: '4.5', streak: 'W3', last10: '7-3' },
        { rank: 3, team: 'Milwaukee Bucks', abbr: 'MIL', w: 40, l: 20, pct: '.667', gb: '8', streak: 'L1', last10: '6-4' },
        { rank: 4, team: 'New York Knicks', abbr: 'NYK', w: 39, l: 22, pct: '.639', gb: '9.5', streak: 'W2', last10: '7-3' },
        { rank: 5, team: 'Orlando Magic', abbr: 'ORL', w: 37, l: 24, pct: '.607', gb: '11.5', streak: 'W1', last10: '5-5' },
        { rank: 6, team: 'Indiana Pacers', abbr: 'IND', w: 36, l: 25, pct: '.590', gb: '12.5', streak: 'L2', last10: '4-6' },
        { rank: 7, team: 'Philadelphia 76ers', abbr: 'PHI', w: 34, l: 26, pct: '.567', gb: '14', streak: 'W1', last10: '6-4' },
        { rank: 8, team: 'Miami Heat', abbr: 'MIA', w: 33, l: 27, pct: '.550', gb: '15', streak: 'L1', last10: '5-5' },
    ],
    western: [
        { rank: 1, team: 'Oklahoma City Thunder', abbr: 'OKC', w: 47, l: 13, pct: '.783', gb: '-', streak: 'W8', last10: '9-1' },
        { rank: 2, team: 'Denver Nuggets', abbr: 'DEN', w: 43, l: 18, pct: '.705', gb: '4.5', streak: 'W2', last10: '7-3' },
        { rank: 3, team: 'Minnesota Timberwolves', abbr: 'MIN', w: 42, l: 19, pct: '.689', gb: '5.5', streak: 'W1', last10: '6-4' },
        { rank: 4, team: 'Dallas Mavericks', abbr: 'DAL', w: 39, l: 22, pct: '.639', gb: '8.5', streak: 'W4', last10: '8-2' },
        { rank: 5, team: 'Los Angeles Clippers', abbr: 'LAC', w: 38, l: 22, pct: '.633', gb: '9', streak: 'L1', last10: '5-5' },
        { rank: 6, team: 'Phoenix Suns', abbr: 'PHX', w: 36, l: 25, pct: '.590', gb: '11.5', streak: 'L3', last10: '4-6' },
        { rank: 7, team: 'New Orleans Pelicans', abbr: 'NOP', w: 35, l: 26, pct: '.574', gb: '12.5', streak: 'W2', last10: '6-4' },
        { rank: 8, team: 'Los Angeles Lakers', abbr: 'LAL', w: 34, l: 27, pct: '.557', gb: '13.5', streak: 'W1', last10: '5-5' },
    ],
};

// ─── Team Stats for Comparison ─────────────────────────────────
export const mockTeamStats = {
    LAL: { name: 'Los Angeles Lakers', abbr: 'LAL', ppg: 117.2, rpg: 44.8, apg: 27.3, fgPct: 48.1, threePct: 36.5, ftPct: 78.2, spg: 8.1, bpg: 5.4 },
    BOS: { name: 'Boston Celtics', abbr: 'BOS', ppg: 120.6, rpg: 45.2, apg: 26.8, fgPct: 49.3, threePct: 38.9, ftPct: 80.1, spg: 7.6, bpg: 5.8 },
    GSW: { name: 'Golden State Warriors', abbr: 'GSW', ppg: 114.8, rpg: 43.1, apg: 29.4, fgPct: 47.2, threePct: 37.8, ftPct: 79.5, spg: 7.9, bpg: 4.9 },
    DEN: { name: 'Denver Nuggets', abbr: 'DEN', ppg: 115.9, rpg: 46.3, apg: 28.7, fgPct: 48.5, threePct: 36.1, ftPct: 77.8, spg: 7.2, bpg: 5.1 },
    MIL: { name: 'Milwaukee Bucks', abbr: 'MIL', ppg: 118.4, rpg: 47.1, apg: 25.6, fgPct: 49.1, threePct: 37.2, ftPct: 76.9, spg: 6.8, bpg: 5.7 },
    PHI: { name: 'Philadelphia 76ers', abbr: 'PHI', ppg: 112.3, rpg: 42.8, apg: 24.9, fgPct: 46.8, threePct: 35.4, ftPct: 81.3, spg: 7.5, bpg: 5.2 },
    DAL: { name: 'Dallas Mavericks', abbr: 'DAL', ppg: 119.1, rpg: 43.5, apg: 26.2, fgPct: 48.7, threePct: 38.1, ftPct: 79.9, spg: 7.1, bpg: 4.6 },
    OKC: { name: 'Oklahoma City Thunder', abbr: 'OKC', ppg: 121.3, rpg: 45.8, apg: 27.9, fgPct: 49.8, threePct: 37.6, ftPct: 78.7, spg: 8.9, bpg: 6.1 },
    MIA: { name: 'Miami Heat', abbr: 'MIA', ppg: 110.5, rpg: 41.2, apg: 25.1, fgPct: 46.1, threePct: 36.8, ftPct: 80.5, spg: 7.8, bpg: 4.3 },
    NYK: { name: 'New York Knicks', abbr: 'NYK', ppg: 113.7, rpg: 46.9, apg: 24.3, fgPct: 47.5, threePct: 35.9, ftPct: 77.4, spg: 6.9, bpg: 5.5 },
    PHX: { name: 'Phoenix Suns', abbr: 'PHX', ppg: 116.2, rpg: 42.4, apg: 27.1, fgPct: 48.9, threePct: 37.4, ftPct: 82.1, spg: 7.3, bpg: 4.8 },
    MIN: { name: 'Minnesota Timberwolves', abbr: 'MIN', ppg: 112.8, rpg: 44.6, apg: 25.8, fgPct: 47.9, threePct: 36.3, ftPct: 79.1, spg: 8.2, bpg: 6.4 },
};

// ─── Player Stats ──────────────────────────────────────────────
export const mockPlayers = [
    {
        name: 'LeBron James',
        team: 'Los Angeles Lakers',
        abbr: 'LAL',
        position: 'SF',
        number: 23,
        stats: { ppg: 25.8, rpg: 7.2, apg: 8.1, spg: 1.2, bpg: 0.6, fgPct: 54.0, threePct: 41.2, ftPct: 75.0 },
    },
    {
        name: 'Nikola Jokic',
        team: 'Denver Nuggets',
        abbr: 'DEN',
        position: 'C',
        number: 15,
        stats: { ppg: 26.4, rpg: 12.4, apg: 9.0, spg: 1.4, bpg: 0.9, fgPct: 58.3, threePct: 35.8, ftPct: 81.7 },
    },
    {
        name: 'Luka Doncic',
        team: 'Dallas Mavericks',
        abbr: 'DAL',
        position: 'PG',
        number: 77,
        stats: { ppg: 33.9, rpg: 9.2, apg: 9.8, spg: 1.4, bpg: 0.5, fgPct: 48.7, threePct: 35.4, ftPct: 78.6 },
    },
    {
        name: 'Giannis Antetokounmpo',
        team: 'Milwaukee Bucks',
        abbr: 'MIL',
        position: 'PF',
        number: 34,
        stats: { ppg: 30.4, rpg: 11.5, apg: 6.5, spg: 1.2, bpg: 1.1, fgPct: 61.1, threePct: 27.4, ftPct: 65.7 },
    },
    {
        name: 'Stephen Curry',
        team: 'Golden State Warriors',
        abbr: 'GSW',
        position: 'PG',
        number: 30,
        stats: { ppg: 26.4, rpg: 4.5, apg: 5.1, spg: 0.9, bpg: 0.4, fgPct: 45.0, threePct: 40.8, ftPct: 92.3 },
    },
    {
        name: 'Jayson Tatum',
        team: 'Boston Celtics',
        abbr: 'BOS',
        position: 'SF',
        number: 0,
        stats: { ppg: 26.9, rpg: 8.1, apg: 4.9, spg: 1.0, bpg: 0.7, fgPct: 47.1, threePct: 37.6, ftPct: 83.5 },
    },
    {
        name: 'Shai Gilgeous-Alexander',
        team: 'Oklahoma City Thunder',
        abbr: 'OKC',
        position: 'SG',
        number: 2,
        stats: { ppg: 30.1, rpg: 5.5, apg: 6.2, spg: 2.0, bpg: 0.9, fgPct: 53.5, threePct: 35.3, ftPct: 87.4 },
    },
    {
        name: 'Joel Embiid',
        team: 'Philadelphia 76ers',
        abbr: 'PHI',
        position: 'C',
        number: 21,
        stats: { ppg: 34.7, rpg: 11.0, apg: 5.6, spg: 1.2, bpg: 1.7, fgPct: 52.9, threePct: 38.8, ftPct: 88.3 },
    },
];

export const allTeams = Object.keys(mockTeamStats).sort();
