// Content for the Methodology page. Every number here was checked against
// the live endpoint or the build script's own output on the date given;
// the award models and the win-probability model are fetched live instead.
// When a model changes, change its entry in the same commit.

export const CHECKED_ON = '2026-09-28';

export const PRINCIPLES = [
    ['Real data only', 'Every number comes from a stored table or a live source; nothing is filled in with placeholders.'],
    ['Held-out checks', 'Predictive models are scored on seasons or games they never trained on.'],
    ['Null results stay in', 'When a model finds nothing (College → NBA Pipeline) or doesn\'t beat a simple baseline (March Madness champions), the page says so.'],
    ['Samples are shown', 'Small samples are flagged or greyed out rather than ranked beside reliable ones.'],
    ['Association is not cause', 'Descriptive studies say what went together, not why.'],
];

// kind: 'model' (predicts), 'index' (a rating built from a formula),
// 'similarity', 'study' (describes what happened).
export const SECTIONS = [
    {
        id: 'predictive',
        title: 'Predictive models',
        blurb: 'Models that output a probability. Each is scored on data it never saw.',
        items: [
            {
                id: 'awards',
                name: 'Award models (MVP, DPOY, ROY, All-NBA)',
                open: { page: 'analytics', hash: 'mvp', label: 'Awards Race' },
                answers: 'Who is on course to win each award this season?',
                method: 'One logistic regression per award on season stats, standardised; random forest and gradient boosting are backtested alongside for comparison. The models are trained with balanced class weights, so their raw outputs run far too high (several players at 99%+ at once). The app shows a calibrated chance instead: for MVP, DPOY and ROY the scores are turned into chances that add up to 100% across the field; for All-NBA (15 selections) they are Platt-scaled to add up to about 15.',
                checked: 'Leave-one-season-out: each past season is predicted by a model trained without it, then compared with the real winner (live table below; Model Validation has the ROC curves). The calibration is fitted on those held-out scores and checked in a nested loop, so no season is scored by a calibration that saw it (live table below).',
                limits: [
                    'The calibration rests on 14 to 16 seasons, so the percentages are approximate; the MVP favourite averaged a 55% chance and won 7 of 15.',
                    'The Prediction Ledger keeps the raw probabilities that were logged before 2026-09-27.',
                    'Voter narrative and the league\'s 65-game eligibility rule are not modelled; DPOY and All-NBA only apply a minutes floor to who counts as a candidate.',
                    'ROY candidates are players in their first NBA season per Basketball-Reference. Until 2026-09-27 the first season in this database was used, which let in 240 players with missing earlier stints (53 in 2025-26); the ROY model was retrained on the corrected pool.',
                ],
                live: 'awards',
            },
            {
                id: 'wp',
                name: 'Win probability (Clutch WPA, Game Replay, Garbage-Time, Guess the Game)',
                open: { page: 'analytics', hash: 'wpa', label: 'Clutch WPA' },
                answers: 'Given the score margin and the time left, how likely is the home team to win?',
                method: 'Logistic regression with isotonic calibration on three inputs (seconds left, home score margin, and margin divided by the square root of time left), trained on play-by-play from 7,232 games (2020-21 to 2025-26). WPA per play = win probability after it minus before it, credited to the player who made it.',
                checked: 'Held out by game, not by play, so a game\'s later plays can\'t leak into training. Brier score, log loss and a reliability curve on the held-out games (live numbers below).',
                limits: [
                    'Possession, timeouts and fouls to give are not inputs, so in a close finish the model can\'t tell who has the ball.',
                    'Covers 2020-21 onward only (the play-by-play on file).',
                    '1.4% of play-by-play events couldn\'t be matched to a player id by name and carry no player credit.',
                    'Clutch-time predictions sit near 50/50, so their scores aren\'t directly comparable with the all-events scores.',
                ],
                live: 'wp',
            },
            {
                id: 'projections',
                name: 'Next-season projections',
                open: { page: 'projections', label: 'Projections' },
                answers: 'What should a simple, fully-stated baseline expect from each current player next season, and how far off is it usually?',
                method: 'Marcel-style: the player\'s last three seasons weighted 5/4/3 (and by their samples), regressed toward the league average of those seasons with the weight on his own numbers N / (N + M), where M is the sample at which the stat is half signal from Stat Stability (for minutes a game and BPM, where real change matters more than in-season noise, M comes from the year-to-year correlation instead), then an age step from the aging curves (level at his age next season minus the level at each past season\'s age). Minutes a game are the exception: the population minutes curve is mostly players gaining and losing a role, so their age step is the average miss of the regressed minutes projection for players of that age and minutes level (bench, rotation, starter), measured on the other backtest seasons. Per-game counts are the projected per-36 rate times projected minutes. Ages come from birth dates (age on February 1) in every season. 34 stats; no projection for a player with under 250 minutes over the three seasons. The 80% range is the 10th to 90th percentile of the same method\'s past errors for players in the same reliability and level bin.',
                checked: 'Every season from 2000-01 to 2025-26 projected from the seasons before it and scored on players who then played 500+ minutes (7,795 player-seasons for points). The projection beats "same as last season" on 31 of 34 stats (median 8% smaller error) and the league average on all 34 (median 51% smaller): points 2.32 a game against 2.46 and 4.69; minutes 3.87 against 4.18 and 6.62; BPM 1.33 against 1.55 and 2.07; 3P% 3.4 points against 4.7 and 3.8. The three it loses to last season are 3-point attempts and makes, because league-wide three-point volume keeps rising and the regression pulls toward past averages. The 80% range held 80% of actuals for every stat, each season judged by the other seasons\' errors; calibration slopes run 0.90 to 1.12. The age step earns its place: without it, points miss by 2.57 and minutes by 4.15. Sniff tests for 2026-27: Dončić 30.6 points (26.6 to 35.2), Wembanyama 25.0 → 25.7 at 23, Jokić 27.7 → 24.3 at 31, LeBron 20.9 → 17.3 at 42; Kennard\'s 47.8% from three regresses to 40.9%. Checked 2026-09-28.',
                limits: [
                    'A baseline that knows nothing about role changes, trades, injuries, a new coach or a player\'s summer. The players still scoring 22+ a game at 34 or older (31 in the backtest) beat it by 3 points a game on average: the aging curve describes the typical player, and they aren\'t one.',
                    'Regression is toward the playing-time-weighted league average, so bench players are pulled a little high for BPM (bias −0.21) and the projection lags the league-wide rise in three-point volume (3PA bias +0.16).',
                    'The backtest scores only players who went on to play 500+ minutes, so it says how the method does for players who kept playing. The M values (2020-21 to 2025-26 data) and the aging curves (all seasons) were not re-estimated per backtest season.',
                    'Rebound %, offensive rebound %, turnover %, usage % and assist % change definition in 2009-10, so no projection mixes seasons from both sides for them. Not projected: on-court ratings and plus-minus, VORP, impact score, games played.',
                ],
            },
            {
                id: 'shotmaking',
                name: 'Expected FG% and shot-making',
                open: { page: 'shotcharts', label: 'Shot Charts' },
                answers: 'How often would an average shooter make this shot, and who shoots better or worse than that on their own shots?',
                method: 'A gradient-boosting classifier (scikit-learn HistGradientBoosting) scores every regular-season shot since 1996-97 (5.93 million) from its court location, distance, angle, zone, two or three, period, seconds left in the period and season. Shot quality is the expected eFG% of a player\'s own shots; shot-making is his actual eFG% minus that, with a binomial 95% range; points above expected is the same gap in points. Every player is scored by a model trained on the other four-fifths of players (5 folds), so his own makes never raise the bar he is measured against. Seasons under 200 attempts are shown but not ranked.',
                checked: 'Chosen on 2025-26, which no candidate saw: log loss 0.648 for boosting against 0.657 for a logistic regression on engineered terms, 0.657 for last season\'s FG% by zone and 0.692 for a constant (live numbers below, with the reliability bins). Cross-fitted over all seasons, the league\'s expected eFG% is within 0.35 points of its actual eFG% in every season. Sniff tests: Curry 2015-16 +13.1 eFG points (1st of 326), Korver 2014-15 +15.1 (1st), Jokić 2024-25 +11.0 (1st of 333); Gobert 2024-25 and DeAndre Jordan 2014-15 have the best shot quality of their seasons with shot-making within a standard error of zero. Year to year, shot quality correlates 0.88 and shot-making 0.56 (players with 200+ attempts in both seasons, 6,866 pairs). Checked 2026-09-28.',
                limits: [
                    'No shot on file has a closest-defender distance or a shot type (catch-and-shoot vs. pull-up), so shot-making also carries the defence a player faced and the shots he created; a rim-runner\'s finishing counts as much as a shooter\'s jumper.',
                    'Before 2010-11 about a quarter of shots (nearly all at the rim) have no exact location and sit at the hoop; the season input lets the model treat them era by era. The stored shot_distance is not used: 7% of threes carry 0 there.',
                    'A shot is far from certain either way (held-out ROC-AUC 0.65), so a season\'s shot-making carries a range of about ± 3-4 eFG points even on 1,000 attempts. A season after the last one in training is scored as that last season.',
                    'Regular season only.',
                ],
                live: 'shotmaking',
            },
            {
                id: 'hotstreaks',
                name: 'Hot Streak Checker',
                open: { page: 'hotstreaks', label: 'Hot Streak Checker' },
                answers: 'Is a player\'s last 5, 10 or 20 games a real change, or the ups and downs every player has?',
                method: 'Two separate answers. How unusual: 4,000 random sets of N games from the player\'s own season so far; the share at least as hot (or cold) is the p-value, shown beside the run\'s percentile among his actual N-game stretches. How much carries on: for every player-season 2020-21 to 2025-26 (player lines rebuilt from play-by-play) and every point in it with 10+ earlier games averaging 15+ minutes, the last N games are compared with his baseline, and so are the next N; the slope of the second gap on the first, across 1.86 million windows, is the share that carried on (95% range from resampling players). Baseline = his games this season before the run plus his previous season counted as a set number of games, chosen per stat and window on held-out data: half a season to a whole one for 3P%, TS% and FT%, 10-20 games for points and usage. Expected next N = baseline + that share of the gap (plus a small league-wide drift).',
                checked: 'Held out 2024-25 and 2025-26 (weights chosen on 2023-24): for all 14 stats and 3 windows, "baseline + share of the gap" predicts the next N games better than either "he\'ll be at his baseline" or "he\'ll keep his last-N rate" (points over 10 games: error 2.80 against 3.15 and 3.15). Shooting runs are mostly noise: 8% of a 5-game 3P% gap carries on, 13% of a 10-game one, 28% of a 20-game one (TS% 8/15/30%), and for shooting the baseline alone predicts almost as well. Role runs last: minutes 56/66/77%, usage 35/49/68%, points 34/48/66%. Sniff test on the league list: as of January 15 of 2023-24, 2024-25 and 2025-26, 11, 10 and 9 players had a 10-game 3P% run significant at p < 0.05, against 9.6, 10.6 and 10.8 expected by chance, and the 25 hottest shooters kept 10-19% of their gap over the next 10 games. Checked 2026-09-28.',
                limits: [
                    'The share is an average across players, not a forecast for one: a run that comes with a new role (more minutes, a teammate injured) lasts longer than one that doesn\'t, so the page shows minutes before and during the run.',
                    'Stat Stability\'s split-half reliability is not used for this: it measures how well a sample separates players from each other, and for per-game counting stats it would say 90-97% of a run lasts (points over 5 games: 0.90 against 0.34 measured).',
                    'Windows are counted at every game, so they overlap; the ranges come from resampling whole players to allow for that.',
                    'Game-by-game data exists only from 2020-21, and games a player sat out don\'t count (a run is his games played).',
                ],
            },
            {
                id: 'splits',
                name: 'Situational splits',
                open: { page: 'splits', label: 'Situational Splits' },
                answers: 'Does a player do better at home, worse on back-to-backs, after long trips, or against strong teams, by more than the average player does?',
                method: 'Every player-season 2020-21 to 2025-26 (player lines rebuilt from play-by-play, joined to the schedule on team and date), four splits: home vs. away; the second night of a back-to-back he also played the first night of vs. 1+ days of team rest; 1,000+ miles traveled since the previous game vs. under 300; that season\'s top-10 vs. bottom-10 teams by average final-score margin. Each side is the ratio of its sums (points per 36 = 36 × points ÷ minutes), the gap is side A minus side B, and its 95% interval treats each game as one draw. The league effect is the average qualified player\'s gap (10+ games a side), weighted by playing time on the smaller side, with a bootstrap interval that resamples whole team-seasons. Two honesty checks per split and stat: how many players stand outside 95% of the league effect against how many do when each player\'s own games are shuffled between the two sides (50 shuffles: what chance produces with these sample sizes), and how well a player\'s gap (vs. average) predicts his gap the next season.',
                checked: 'League effects, all six seasons pooled: home court is worth +0.23 points per 36 (95% +0.16 to +0.30) and +0.9 TS points, and it was smallest in 2020-21, played mostly without fans (+0.07, range crossing zero). Against top-10 teams players score 1.09 fewer points per 36 and shoot 2.2 TS points worse than against bottom-10 teams. On back-to-backs, the players who play both nights get 0.65 more minutes and shoot the same (TS -0.2 points, range crossing zero): the stars rested on second nights leave minutes to others. Across the 44 split-and-stat pairs, 4,944 player-seasons stood out against 4,544 with the games shuffled (and 3,666 at a flat 5%: a dozen back-to-backs is a small sample, so the shuffle is the fair baseline). 41 of the 44 year-to-year correlations are below 0.1; the highest are blocks (0.18) and three-point attempts (0.16) against strong vs. weak teams, and minutes on back-to-backs (0.17). Checked 2026-09-28.',
                limits: [
                    'Descriptive, not causal: a split mixes the situation with who else played (load management on back-to-backs), the score (blowouts against weak teams cut starters\' minutes) and the schedule.',
                    'Long trips end in a home game 38% of the time, short ones 77%, so the travel split partly measures home court; the page also shows the league effect with home/away held equal (points per 36: -0.28 raw, -0.15 held equal).',
                    'Opponent strength is the whole season\'s margin, including the game itself. Rest and travel are the team\'s schedule; a back-to-back he sat the first night of is in neither side.',
                    'Game-by-game data exists only from 2020-21, regular season only.',
                ],
            },
            {
                id: 'madness',
                name: 'March Madness model',
                open: { page: 'analytics', hash: 'madness', label: 'March Madness' },
                answers: 'Pre-tournament odds for every team in the NCAA bracket.',
                method: 'Opponent- and venue-adjusted scoring margin (ridge least squares on every D1 game before the tournament), logistic regression on the difference between two teams, 20,000 simulations of the real bracket.',
                checked: 'Five input sets compared by leave-one-season-out log loss on 2013-2025 (801 games); adjusted margin alone won (0.557). 2026 was held back entirely and run once: Michigan won; the model had them 3rd (18.9%).',
                limits: [
                    'Better calibrated than seeds game by game, but not better at finding the champion: the champion was its favourite in 2 of 12 backtest seasons, and a 1 seed in 9.',
                    'Torvik\'s end-of-season ratings are never used as inputs: they include the tournament.',
                ],
            },
        ],
    },
    {
        id: 'indexes',
        title: 'Ratings and indexes',
        blurb: 'Formulas that turn data into one number. Each says what it leaves out.',
        items: [
            {
                id: 'bpm',
                name: 'BPM and VORP',
                open: { page: 'analytics', hash: 'impact', label: 'Impact Rankings' },
                answers: 'How much a player adds per 100 possessions (BPM), and in total over a replacement player (VORP).',
                method: 'Basketball-Reference\'s published values, loaded for every season; 2009-10 onward is linked to NBA ids through the project\'s id map (7,273 of 7,279 rows; the 6 unlinked are left empty).',
                checked: 'Games played agree within one game on every linked row, an independent check of the id link.',
                limits: [
                    'Until 2026-09-27 the app used its own BPM reproduction, which ran hot (2025-26 SGA at 22.0 vs the published 11.7). It is kept only as an input to Pair Synergy, whose trained model was fitted on it.',
                    'Box-score based: defence away from the ball is only partly captured.',
                ],
            },
            {
                id: 'rapm',
                name: 'RAPM (regularized adjusted plus-minus)',
                open: { page: 'rapm', label: 'RAPM' },
                answers: 'What does each player add per 100 possessions once the other nine players on the floor are held constant?',
                method: 'One row per side per tracked five-man stint (lineup_stints, 2020-21 to 2025-26): the offence\'s points per 100 possessions in the stint, weighted by those possessions, regressed on +1 for its five players\' offence columns, −1 for the five defenders\' defence columns, a season intercept and a home term. Ridge regression shrinks every player toward zero (the league average) with a strength λ chosen by 5-fold cross-validation grouped by game; λ = 3,000 in every season, and the curve is flat (the held-out error at the choice is about 0.2 points per 100 under everyone-average, out of about 61, because single stints are mostly noise). Three versions: one season; a three-season window (one rating per player over the window, one intercept per season; windows end 2022-23 to 2025-26); and one season shrunk toward a scaled Basketball-Reference BPM (offence toward OBPM, defence toward DBPM) instead of zero. For that last version λ is kept at the single-season value and only the scale (0.75 or 1) is cross-validated, because with λ free the cross-validation minimum slides to the top of any grid (128,000 here), which is BPM itself; both the choice and the minimum are stored and shown on the page. Standard errors and 95% intervals come from 300 refits on games resampled with replacement. Rows under 1,000 possessions are flagged, not hidden.',
                checked: 'Two tests, both stored (rapm_validation). Within each season, each fifth of the games is predicted by a fit on the other four. Without any leak, each season\'s stints are predicted from the earlier season\'s ratings used as published, with only the intercept and home term refitted. Predicting 2025-26 game margins from 2024-25 ratings: BPM 15.33 points RMSE, three-season RAPM 15.46, BPM-prior RAPM 15.53, plain one-season RAPM 15.90, everyone-average 16.78, and on/off used as published 21.31 (its best-fitting scale is 0.09 to 0.20: on/off overstates a player\'s effect five to ten times over). Predicting 2024-25 from 2023-24 the order flips slightly (BPM-prior 14.85, three-season 14.88, one-season 15.04, BPM 15.12). So RAPM with a prior or a three-season window predicts about as well as BPM, and plain one-season RAPM a little worse: the known result, stated on the page. Year to year, one-season RAPM correlates 0.35 to 0.41 with itself, the BPM-prior version 0.61 to 0.67, BPM 0.73 to 0.81, on/off 0.23 to 0.34. Sniff tests: the home edge is +0.95 per 100 possessions in the fan-less 2020-21 season and +1.5 to +2.5 after; Jokić is top-6 in one-season RAPM every season from 2021-22 (2nd in 2022-23 and 2023-24), 1st in every three-season window from 2023-24 and 1st or 2nd in the BPM-prior version every season, while in 2020-21 he ranks 69th (+1.8 ± 1.0) because the Nuggets were +0.5 without him that season; the correlation with BPM among qualified players is 0.56 to 0.60; in 2024-25 Draymond Green is 8th by RAPM and 129th by BPM, Herb Jones 53rd and 340th. Checked on 2026-09-29.',
                limits: [
                    'One season of stints can\'t separate players who nearly always share the floor: the shrinkage splits their joint effect between them, and the intervals say so.',
                    'Shrinkage compresses everyone toward zero: a +5 is elite, and stars sit far under their on/off. That is what the data supports, not a scale error.',
                    'The within-season held-out numbers flatter BPM (a full-season value that saw the held-out games) and slightly flatter RAPM (λ was chosen on the same folds); the next-season test has neither problem.',
                    'Only stints that reconciled with five identified players a side are used (93.7 to 99.8% of minutes a season). Rookies and newcomers have no earlier-season rating in the next-season test and count as average for every model.',
                ],
            },
            {
                id: 'dad',
                name: 'DAD Index (Defensive Assignment Difficulty)',
                open: { page: 'analytics', hash: 'dad', label: 'DAD Index' },
                answers: 'How hard were the players each defender actually guarded?',
                method: 'Share of the defender\'s tracked possessions against each opponent × that opponent\'s offensive BPM (Basketball-Reference). Opponents under 500 minutes count as replacement level (−2.0). Z-scored per season, with a within-position version.',
                checked: 'Year-over-year stability r = 0.70 for 243 defenders qualified in both 2024-25 and 2025-26.',
                limits: [
                    'Describes assignments, not a full defensive rating: no help defence, rebounding or scheme.',
                    'Matchup pairs under 5 partial possessions were dropped when the data was fetched.',
                    'Qualified defenders only (1,000+ partial possessions).',
                ],
            },
            {
                id: 'rim',
                name: 'Rim Deterrence',
                open: { page: 'analytics', hash: 'rim', label: 'Rim Deterrence' },
                answers: 'Do opponents stop going to the rim, and miss more when they do, with a given defender on the floor?',
                method: 'Every field-goal attempt of every regular-season game 2020-21 to 2025-26, from the same ESPN play-by-play parser as the player lines and the five-man stints, placed in its stint by its event number (lineup_stints; only stints that reconciled with five identified players a side). Distance comes from the NBA\'s own shot chart: each ESPN attempt is matched to the same shot in player_shots by order within game, shooter and period when both feeds list the same attempts with the same make/miss sequence (the two feeds\' clocks differ by up to ~26 seconds for the same shot, so clocks can\'t be used), and the distance is taken from the x/y coordinates. Unmatched attempts use ESPN\'s "N-foot" text; a layup, dunk, tip or putback with neither counts as 0-3 ft; any other two stays "distance unknown". A three is the NBA\'s shot type where matched, the parser\'s call otherwise. Bands: 0-3 ft (under 4 ft, about the restricted area), 4-9, 10-15, 16 ft to the arc, threes. On = opponents\' attempts with him among the five defenders; off = his team\'s other tracked stints in the games he played. Per 100 possessions uses FGA + 0.44 FTA − OREB + TOV averaged over both sides, as On/Off. Rim points per 100 = 2 × rim makes per 100 (fouls and and-ones not counted). 95% intervals come from resampling his games 2,000 times. Rows under 1,000 minutes are flagged, not hidden.',
                checked: 'Every one of the 1,283,689 attempts falls in exactly one stint, and every stint\'s attempts equal its stored FGA (0 mismatches). 99.0% of attempts are matched to the NBA shot chart (97.4 to 99.6% a season; 2025-26 is lowest: player_shots lacks four of its games, and a few thousand more of its attempts don\'t line up shot for shot with ESPN\'s). The league\'s rim share of attempts matches player_shots\' own coordinates to 0.1 point every season (30.1% in 2020-21, 28.3% in 2025-26). The no-distance rule, measured on the 302,060 matched shots where both are known, is right 85.8% of the time; the rest are 4-9 ft drives, so the rule would overstate rim attempts, which is why coordinates come first (the rule places under 0.5% of attempts). The parser\'s two-or-three call agrees with the NBA\'s on 99.2% of matched shots. Signal against noise, among players with 1,000+ minutes: 15 to 20% of them a season have a rim-attempts gap whose interval clears zero, 10 to 16% a rim FG% gap, 17 to 23% a rim-points gap, against 5% by chance. Year to year (948 player pairs, 1,000+ minutes both seasons) the attempts gap correlates 0.34 with itself, the rim FG% gap 0.17, the rim-points gap 0.36. His own blocks per 36 correlate −0.31 with the rim FG% gap and only −0.13 with the attempts gap. Sniff tests (ranks among 1,000+ minute players, 1 = biggest drop in rim points): Rudy Gobert 2nd, 2nd, 1st, 3rd, 1st and 22nd from 2020-21 to 2025-26; Victor Wembanyama 41st as a rookie, 3rd in 2024-25 (2nd in rim attempts), 12th in 2025-26; Brook Lopez 5th in 2022-23 and 5th in rim FG% in 2023-24, but mid-pack in rim attempts most seasons. Listed centers average −0.7 rim points per 100, everyone else +0.5. Checked on 2026-09-29.',
                limits: [
                    'On/off, not adjusted: a second big on the floor, switchable wings, his backup and the opponents\' units he faced all move it. The extremes are often small samples or thin benches (Daniel Theis in 38 games for the 2024-25 Pelicans leads that season at 500+ minutes).',
                    'Rim FG% differences are mostly noise year to year (r 0.17); the attempts gap is the more repeatable half.',
                    'Shot defence only: no fouls drawn, free throws, turnovers forced or rebounds, and no tracking data on who contested a shot.',
                    'Stints with a player ESPN gives no id to, and games whose play-by-play didn\'t reconcile, are left out (the tracked share is 93.7 to 99.8% of attempts a season).',
                ],
            },
            {
                id: 'assists',
                name: 'Assist Network',
                open: { page: 'assists', label: 'Assist Network' },
                answers: 'Who sets up whom on a team, on what kind of shot, and how much of each player\'s scoring is set up by someone else?',
                method: 'Every made field goal of every regular-season game 2020-21 to 2025-26 from ESPN\'s play-by-play, read by the same parser as the Game Log (scripts/pbp_lineups.py). ESPN names the passer in the made shot\'s text ("... (Jamal Murray assists)"); the parser matches that name to an NBA id the way it does for the player lines (the game\'s own players, then that season\'s team rosters, then names only one player has had). A basket is two or three as the parser calls it; its kind comes from ESPN\'s shot type: layups and dunks (with alley-oops, finger rolls, tips), floaters and hooks, other two-point jumpers, threes. Assisted share = assisted makes / all makes of that kind. The three NBA Cup finals are left out (they don\'t count in regular-season stats). The network draws the top players by minutes around a circle, one arrow per passer → scorer pair, width = assists.',
                checked: 'Every player-season\'s assists equal his Game Log assists (0 of 3,172 player-seasons differ), and the parser\'s season assists are within 0.3% of NBA.com\'s (0.997 to 1.001 of the season totals, players with 20+ games). 601,617 made field goals, 373,076 of them assisted: 60.2 to 63.7% a season, 50 to 54% of made twos and 82 to 85% of made threes. 1,149 assisted baskets (0.31%) name a passer ESPN gives no id to and aren\'t in any pair; 4 plays are left out as data errors (3 players credited with assisting themselves). Sniff tests: the league\'s top pair each season is Draymond Green → Stephen Curry (194, 2020-21), Trae Young → Clint Capela (164), James Harden → Joel Embiid (244), Tyrese Haliburton → Myles Turner (215), James Harden → Ivica Zubac (209) and Jamal Murray → Nikola Jokić (171, 2025-26); Green → Curry is Golden State\'s top pair every season; Nikola Jokić → Aaron Gordon led Denver in 2022-23 (155, 131 of them layups and dunks). Creators: 12 to 19% of Harden\'s made twos were assisted each season, 7 to 22% of Shai Gilgeous-Alexander\'s, 10 to 26% of Luka Dončić\'s. Shooters: 89 to 94% of Klay Thompson\'s made threes, 88 to 100% of Duncan Robinson\'s. Checked on 2026-09-29.',
                limits: [
                    'An assist is the scorekeeper\'s call, and home scorekeepers are known to differ in how freely they give them; nothing here adjusts for that.',
                    'Counts, not rates per chance: a pair on the floor together more has more assists. The network shows who connects, not how efficiently.',
                    'Assisted threes are the norm (82 to 85% league-wide), so a shooter at 94% is only mid-pack among 50+ make shooters; the 2s share separates creators from finishers more clearly.',
                    'Shot kind comes from ESPN\'s shot type, not distance; a "jump shot" two can be from 8 feet or 22.',
                ],
            },
            {
                id: 'gravity',
                name: 'Gravity Index and Spacing Lab',
                open: { page: 'analytics', hash: 'spacing', label: 'Spacing Lab' },
                answers: 'How much does a shooter pull the defence, and do well-spaced lineups score more?',
                method: 'A proxy, not tracking gravity: 3PA per 100 possessions, catch-and-shoot 3P% and the share of threes taken with a defender within 6 ft, each z-scored within the season (500+ minutes) and summed. Lineup spacing = the five players\' sum.',
                checked: 'Offensive rating of 4,250 lineups (100+ possessions, 2013-14 to 2025-26) regressed on spacing plus the five players\' summed OBPM, season fixed effects, errors clustered by team-season: +0.074 ORtg per spacing point (95% CI 0.014 to 0.134, p = 0.016).',
                limits: [
                    'The effect is small: spacing adds 0.001 to R² once lineup quality is in the model.',
                    'An association across lineups, not a forecast for a specific five.',
                ],
            },
            {
                id: 'contracts',
                name: 'Contract Value',
                open: { page: 'analytics', hash: 'contracts', label: 'Contract Value' },
                answers: 'Is a player worth their salary?',
                method: 'WAR = published VORP × 2.7, rescaled per season so positive WAR adds up to the league\'s real wins above replacement (factor 0.77 to 0.80). Fair value = WAR × that season\'s cost per win + the league minimum.',
                checked: 'Cost per win is built from real salaries, real team records and the real minimum salary for each season: $2.08M per win in 2005-06 up to $6.11M in 2024-25.',
                limits: [
                    'Salary data is third-party (Kaggle uploads built from HoopsHype and Basketball-Reference) and imperfect.',
                    'Covers 2005-06 to 2016-17, 2018-19, 2019-20 and 2024-25 only.',
                    'Only players who played are priced.',
                ],
            },
            {
                id: 'tradeimpact',
                name: 'Trade Impact',
                open: { page: 'tradeimpact', label: 'Trade Impact' },
                answers: 'For a 1-for-1 trade, what happens to each team\'s projected wins, starting-five spacing, payroll and surplus?',
                method: 'Nothing new is estimated. Projected win% is the Trade Analyzer\'s regression on the roster\'s minute-weighted net rating and TS% (players keep their own season stats). Spacing is the Gravity Index summed over the team\'s most-used real five-man lineup, with the incoming player in the outgoing player\'s spot (or the lowest-minute starter\'s spot if the outgoing player wasn\'t in that five). Payroll and surplus are Contract Value\'s, summed over the players with matched salaries who played for the team.',
                checked: 'Each piece carries its own validation (see the Gravity and Contract Value cards; the win model is leave-one-season-out R² 0.92, about 2.5 wins of error over 82 games). Checked on a real 2024-25 case: the Knicks\' most-used five is their real starting five (1,939 possessions), and swapping Josh Hart for Duncan Robinson moves its spacing from the 81st to the 97th percentile while payroll changes by the real $1.26M salary difference.',
                limits: [
                    'Role, usage and minutes changes after a trade are not simulated; the win change is a roster-production estimate.',
                    'Spacing is a proxy with a small validated effect on offensive rating; the starting five after the trade is an assumption stated on the page.',
                    'Payroll is the priced on-court payroll, not the cap sheet, and only for seasons with reliable salary data (2005-06 to 2016-17, 2018-19, 2019-20, 2024-25). 2024-25 is the only season with all three blocks after 2019-20.',
                    'One-for-one trades only.',
                ],
            },
            {
                id: 'rolefinder',
                name: 'Role Player Finder',
                open: { page: 'rolefinder', label: 'Role Player Finder' },
                answers: 'Which players best fit a role such as 3-and-D wing or rim protector?',
                method: 'Score = the sum of weight × z-score over a role\'s components, within one season among players with 500+ minutes (2017-18 on, when every input exists). DAD and Gravity components use those tables\' stored z-scores; blocks and steals per 36, rebound, assist, usage and turnover rates, true shooting, BPM parts and the defended-FG% differential are z-scored here. "Compare with the chosen positions" re-scores everything within the selected positions. Scouting Report findings are shown as fit flags, not scored.',
                checked: 'The presets\' weights are a judgment call, written down and shown in full on the page, not fitted to anything. Sniff tests on 2024-25: rim protector puts Wembanyama, Holmgren and Kessler 1-2-3; point-of-attack puts Caruso, Ausar Thompson and Dyson Daniels 1-2-3; floor spacer starts Beasley, Isaiah Joe, Curry; 3-and-D starts Dort, Finney-Smith, Caruso, with Anunoby 2nd in 2025-26.',
                limits: [
                    'Known misses: Rudy Gobert ranks about 20th as a rim protector because his deterrence shows up as few blocks and a modest defended-FG% effect; Brook Lopez sits mid-pack as a stretch big on 2024-25 volume.',
                    'A player missing a weighted component (under 1,000 tracked defensive possessions, or under 2 three-point attempts a game for 3P%) is left out, not treated as average; the page counts them.',
                    'Salary filtering only exists for the seasons with contract data (2017-18 to 2019-20 and 2024-25).',
                ],
            },
            {
                id: 'garbage',
                name: 'Garbage-Time Deflator',
                open: { page: 'analytics', hash: 'garbage', label: 'Garbage-Time Deflator' },
                answers: 'How much of a player\'s scoring came when the game was already decided?',
                method: 'Every play gets a leverage index from the win-probability model (average play = 1.0). Garbage time = win probability above 99% either way, or a margin of 18+ in the second half or overtime.',
                checked: 'Buckets are applied in a fixed order and their shares are shown; the "stat-padding" badge is only given at the 90th percentile or above among 40+ game players.',
                limits: [
                    'ESPN play-by-play only, 2020-21 to 2025-26.',
                    'Thresholds are choices, stated on the page, not facts.',
                ],
            },
            {
                id: 'helio',
                name: 'Heliocentricity Index',
                open: { page: 'analytics', hash: 'helio', label: 'Heliocentricity' },
                answers: 'Whose team\'s offence runs through them most?',
                method: 'The average of four percentile ranks within the season: time-of-possession share, touches, usage and assist percentage.',
                checked: 'Descriptive only; the weights are equal on purpose and disclosed.',
                limits: ['Not predictive and not a measure of value: a high score can be good or bad for a team.'],
            },
            {
                id: 'era',
                name: 'Era Translator',
                open: { page: 'era', label: 'Era Translator' },
                answers: 'What would a season from one era look like in another season\'s game?',
                method: 'Two restatements. Pace only: each per-game count × (target league pace ÷ source league pace), percentages unchanged. Pace + league: each count × (target ÷ source league average per team game for that stat), so the player keeps the same share of an average team\'s output; percentages move by the change in league average; threes stay pace-only. Beside them, the era-free view: z-score and percentile within the player\'s own season. League averages are Basketball-Reference\'s.',
                checked: 'Checked 2026-09-28: Oscar Robertson 1961-62 (30.8 / 12.5 / 11.4) restates to 24.3 / 9.8 / 9.0 at 2025-26\'s pace, against 24.5 / 9.9 / 9.1 from Neil Paine\'s published per-100-possession line at the same pace and minutes; Wilt\'s 50.4 points becomes 39.7.',
                limits: [
                    'Pace before 1973-74 is an estimate (offensive rebounds and turnovers weren\'t recorded); 1949-50 is estimated by this app.',
                    'League pace, not the team\'s: Wilt\'s 1961-62 Warriors played faster than the league, so his restated line is about 4% too high.',
                    'The two answers differ a lot for points (39.7 vs 49.0 for Wilt): neither says how a player would have adapted to another era\'s rules, spacing or athletes.',
                ],
            },
        ],
    },
    {
        id: 'similarity',
        title: 'Similarity and clustering',
        blurb: 'Grouping and matching players. Every stat is compared within its own season first, so eras compare fairly.',
        items: [
            {
                id: 'similarity',
                name: 'Season Similarity',
                open: { page: 'analytics', hash: 'similarity', label: 'Season Similarity' },
                answers: 'Which player-seasons look most like this one?',
                method: 'Eight numbers per season (points, true shooting, usage, net rating, assist %, rebound % z-scored within the season, plus age and minutes), standardised, compared by cosine similarity.',
                checked: 'The live view was checked against the stored top 10 for all 7,279 seasons: identical scores and lists. A smoke test re-checks one season on every run.',
                limits: [
                    '2009-10 onward only: usage and net rating aren\'t on file before that.',
                    'Cosine compares shape, so a smaller version of the same profile can still score high; the stat line is shown next to each match for that reason.',
                ],
            },
            {
                id: 'statline',
                name: 'Stat Line Finder',
                open: { page: 'statline', label: 'Stat Line Finder' },
                answers: 'Which real player-seasons are closest to a stat line I type?',
                method: 'Each stat (points, rebounds, assists, steals, blocks, turnovers, 3PA, 3P%, FT%, TS%, usage, assist %, rebound %, net rating, minutes, age) is z-scored within its own season over every player-season that has it; shooting percentages only over players above the Leaderboard Builder\'s attempts floor. The typed line is z-scored against the season the user picks, and every player-season is ranked by the root-mean-square gap in z-scores over the typed stats only (0 = the same standing on every stat). Levels are matched, not the shape of the profile as in Season Similarity.',
                checked: 'Typing a real season\'s own line in its own season returns that season first at distance 0 (Curry 2015-16, LeBron James 2012-13, Wilt Chamberlain 1961-62; checked 2026-09-28, and a smoke test re-checks Curry and Wilt on every run). 3 blocks and 12 rebounds today returns Olajuwon 1992-93, Camby, Mutombo, Wembanyama and Robinson.',
                limits: [
                    'Standing is era-relative, so a match from another era can show raw numbers unlike the typed ones (60% TS today matches 52% TS in 1975-76, when the league shot worse).',
                    'Each stat counts equally; there are no weights. A stat is only usable from its first well-recorded season (steals and blocks 1973-74, threes 1979-80, net rating 2009-10).',
                    'A line far outside anything real (Wilt\'s 50 and 26 read in 2025-26) still returns the nearest seasons; the page warns when the best match is more than one standard deviation away.',
                ],
            },
            {
                id: 'roles',
                name: 'Player Roles',
                open: { page: 'analytics', hash: 'archetypes', label: 'Player Archetypes' },
                answers: 'What kind of player is this, judged by what they do with their minutes?',
                method: 'K-Means on rate stats and shot-location shares, z-scored within each season: 5,386 player-seasons 2010-2026 (15+ minutes, 20+ games, 100+ located shots).',
                checked: 'Ten roles is the most whose grouping survives refitting on 80% subsamples (adjusted Rand 0.83; 11 or more drop to 0.52-0.64).',
                limits: ['Separation is low at every K (silhouette 0.10): playing styles are a continuum, and many players sit between two roles.'],
            },
            {
                id: 'offstyle',
                name: 'Offensive Style',
                open: { page: 'analytics', hash: 'archetypes', label: 'Player Archetypes' },
                answers: 'How does a player\'s offence get generated?',
                method: 'K-Means on play-type shares (isolation, pick-and-roll, spot-up, post-up, transition, roll man), era-normalised.',
                checked: 'Silhouette 0.21, disclosed as weaker separation than the stat-based groups.',
                limits: ['Play-type mixes overlap a lot; treat the style as a tendency.'],
            },
            {
                id: 'prospects',
                name: 'Draft Prospect Comp Finder',
                open: { page: 'analytics', hash: 'prospects', label: 'Draft Prospects' },
                answers: 'Which past college players does a prospect resemble, and how did they do in the NBA?',
                method: 'Around 105,000 D1 player-seasons, era-normalised, matched by similarity; optional combine measurements.',
                checked: 'NBA outcomes shown only where a real name match exists.',
                limits: ['About 55% of NBA rookies since 2015 have a US college record; international and G League players never appear.'],
            },
        ],
    },
    {
        id: 'studies',
        title: 'Descriptive studies',
        blurb: 'What happened, measured carefully. None of these claims a cause.',
        items: [
            {
                id: 'clutch',
                name: 'Clutch vs. non-clutch',
                open: { page: 'analytics', hash: 'wpa', label: 'Clutch WPA' },
                answers: 'Does a player do better or worse in clutch time than in the rest of the game?',
                method: 'Each play\'s WPA divided by its leverage (the win-probability value of one point at that moment, from the win-probability model), summed over a player\'s shots, free throws and turnovers: WPA per scoring chance, in points, at equal leverage. Clutch lift = clutch rate − non-clutch rate − the league\'s own change (0.843 vs 0.914), with a 95% interval clustered by game.',
                checked: 'The unit reads as points: the league\'s 0.914 per chance outside clutch time sits inside its real points per (FGA + FTA + TOV), 0.90-0.93 in 2020-21 to 2025-26. With 100+ clutch chances, 14 of 186 players land outside zero at 95%, where about 9 would by chance; lift divided by its standard error has an SD of 1.09 (1.0 would be pure noise). Checked 2026-09-28.',
                limits: [
                    'Clutch plays swing win probability 3.7 times as much as an average play, so raw clutch WPA mostly counts how many clutch plays a player got; the lift removes that.',
                    'The model doesn\'t know who has the ball, so a miss or turnover costs nothing: this measures scoring, not defense or decisions.',
                    'Pooled over 2020-21 to 2025-26, not per season.',
                    'About 1 in 20 players clears the 95% bar by chance, so one "better" or "worse" verdict is weak evidence.',
                ],
            },
            {
                id: 'pipeline',
                name: 'College → NBA Pipeline',
                open: { page: 'analytics', hash: 'pipeline', label: 'College Pipeline' },
                answers: 'Do players from stronger college teams outperform their draft slot?',
                method: 'Win Shares in the first four NBA seasons compared with a draft-slot expectation fitted on 598 picks (2013-2022).',
                checked: 'Bootstrap intervals on every group; 478 college players from classes old enough to judge.',
                limits: ['A null result: +0.38 Win Shares per 10 points of team margin (95% range −0.30 to +1.04, r = 0.05). Once you know the pick, college team strength barely matters.'],
            },
            {
                id: 'draft',
                name: 'Draft Value',
                open: { page: 'draft', label: 'Draft Value Guide' },
                answers: 'What is a draft slot usually worth?',
                method: 'Basketball-Reference Win Shares in each pick\'s first five NBA seasons, draft classes 1980-2021.',
                checked: 'Slot averages 23.6 / 14.4 / 8.4 / 3.9 / 1.9 Win Shares for picks 1-5 / 6-14 / 15-30 / 31-45 / 46-60; career totals spot-checked against Basketball-Reference.',
                limits: ['Win Shares lean on team results, especially on defence; five seasons misses late bloomers.'],
            },
            {
                id: 'referees',
                name: 'Referee Tendencies',
                open: { page: 'analytics', hash: 'referees', label: 'Referee Tendencies' },
                answers: 'Do games an official works produce more fouls, free throws or pace than usual?',
                method: 'Each official\'s games compared with the league average for the same seasons, with a 95% confidence interval on the difference.',
                checked: 'Officials with under 25 games are flagged as a small sample, not ranked.',
                limits: ['Crew assignment, opponents and era are unmeasured; coverage grows as the resumable fetch is re-run.'],
            },
            {
                id: 'matchups',
                name: 'Matchup Finder',
                open: { page: 'analytics', hash: 'matchups', label: 'Matchup Finder' },
                answers: 'Which defenders hold a scorer down, and who torches whom?',
                method: 'NBA player-vs-player matchup tracking, 2017-18 to 2025-26 (571,608 rows).',
                checked: 'Pairs under 20 partial possessions are greyed out and marked small sample.',
                limits: ['One defended shot is 0% or 100%: small pairs are noise even when shown.'],
            },
            {
                id: 'stints',
                name: 'Five-man stints from play-by-play',
                open: { page: 'analytics', hash: 'pairs', label: 'Pair Chemistry' },
                answers: 'Who was on the floor for every minute of every game since 2020-21, and what happened while they were?',
                method: 'Every regular-season game 2020-21 to 2025-26 is replayed from ESPN play-by-play with the same lineup parser that builds the player game lines (scripts/pbp_lineups.py): a period\'s starters are the players who do anything before checking in, then every substitution swaps two players. A stint is a stretch of one period with the same ten players; it carries each side\'s points and possession components (FGA + 0.44 FTA − OREB + TOV, the on/off credit rules) and the range of events inside it. Points come from the made shots and free throws themselves; in games where those don\'t add up to the real final score (a shot the text gives no type for), the running maximum of ESPN\'s score fields is used instead, because crediting positive score changes double-counts in the few hundred games where the score field is stale. Each game is reconciled against the real final score, its length and the team-game totals; each stint must have five identified players a side. Lineup and pair tables are built from the stints that pass.',
                checked: '7,220 of 7,232 games reconcile on points, seconds and possessions (the 12 that don\'t: 3 NBA Cup finals not in the scores table, one game whose play-by-play stops after three periods, 6 missing their last few points, 2 with a rebound credited to the wrong side). Tracked minutes are 93.7% (2020-21), 93.9%, 97.2%, 96.1%, 97.8% and 99.8% (2025-26) of each season; the rest is time with a player ESPN gives no id to (two-way and 10-day players missing from player_season_stats, the parser\'s only id source). Every player\'s stint seconds equal his game-line seconds in all but 9 of 152,471 player-games. Each team\'s five most-used lineups match stats.nba.com\'s stored minutes at r 1.000 (median gap 0.8-1.1 minutes) and their net ratings at r 0.98-0.99 every season. Checked on 2026-09-28.',
                limits: ['Coverage is per team: the page lists the games excluded and the minutes left out. Nothing is adjusted for opponents.', 'Possessions are averaged over the two sides, so ratings sit about 3 points under NBA.com\'s scale; differences don\'t depend on that.', 'A player with no id in the play-by-play can\'t be placed on the floor: 2-6% of minutes a season before 2025-26. Adding an id fallback would change player_game_lines and everything built on it, so it is a separate job.'],
            },
            {
                id: 'lineups',
                name: 'Lineup Chemistry and With vs. Without',
                open: { page: 'analytics', hash: 'lineups', label: 'Lineup Chemistry' },
                answers: 'How did real five-man units, and teams with and without a star, actually do?',
                method: 'Real lineup ratings with a stated minutes cutoff, from every play-by-play stint from 2020-21 on and from stats.nba.com\'s stored 2,000 most-used lineups before that (the page names the source); team results split by whether a player played.',
                checked: 'The 2023-24 76ers with and without Embiid (79.5% vs 37.2% wins) reproduce that season\'s known story. The 2025-26 Thunder\'s most-used lineup has 155 tracked minutes here against 167 stored by stats.nba.com; the gap is one game excluded because its play-by-play is missing six points. Checked on 2026-09-28.',
                limits: ['Other absences and opponents aren\'t controlled for; small lineups are noisy, and at a low minutes floor the top of the list is small samples.', 'With vs. Without fetches its games live from stats.nba.com, whose per-game point differential is summed player plus-minus ÷ 5: in 160 of 20,348 games 2009-10 to 2025-26 it isn\'t the final margin (134 by a point or more), so its average point differential can be off by a fraction of a point. Wins and losses are right.'],
            },
            {
                id: 'pairs',
                name: 'Pair Chemistry',
                open: { page: 'analytics', hash: 'pairs', label: 'Pair Chemistry' },
                answers: 'How did a team do with each pair of its players on the floor together?',
                method: 'From 2020-21 on, every play-by-play stint containing both players, summed (pair_seasons): minutes and possessions added up, points per 100 possessions on each end. Before that, every stored five-man lineup containing both players (lineup_stats), with ratings weighted by possessions. Colours compare each pair with the team over the same minutes; pairs under a shared-minutes floor (default 100) are greyed out.',
                checked: 'The 2023-24 Nuggets (57-25) from stints: Jokić and Murray shared 1,410 tracked minutes at +14.6, and 97% of the team\'s minutes are tracked (110 minutes in 22 games had a player with no id). The 2015-16 Warriors from the stored lineups: Curry and Green are the most-shared pair (2,179 stored minutes, +19.8) and the top three pairs with 500+ shared minutes all include Iguodala; no player\'s stored minutes exceed their season minutes. Checked on 2026-09-28.',
                limits: ['Before 2020-21 only the league\'s 2,000 most-used lineups a season are stored: 31-89% of a team\'s minutes (median 65%), with bench units missing most, so a team\'s figure over these lineups runs above its real net rating. From 2020-21 the page lists the games excluded and the minutes left out instead.', 'Descriptive: not adjusted for opponents or for the other three players on the floor.'],
            },
            {
                id: 'onoff',
                name: 'On/Off for every player',
                open: { page: 'analytics', hash: 'onoff', label: 'On/Off' },
                answers: 'How did a team do with a player on the floor, and without him, over every minute of the season?',
                method: 'Every regular-season game 2020-21 to 2025-26 rebuilt from ESPN play-by-play into who was on the floor for each event (the same player lines as Stat Stability). On-court: the team\'s and the opponent\'s points and possessions while he played. Off-court: the team\'s game totals minus his on-court totals, game by game, over the games he played. Possessions = FGA + 0.44 FTA − OREB + TOV, averaged over the two sides. The on − off net rating carries a 95% interval from resampling his games 2,000 times (a game-clustered bootstrap); rows under 500 minutes are flagged, not hidden. The Stars view names each team\'s top-usage player with 1,000+ minutes and shows the team with and without him.',
                checked: 'On + off possessions equal the team\'s game total by construction, and the rebuilt lineups track 99.1-100% of player-minutes a season. The league\'s possession-weighted on-court net rating is within ±0.07 of zero every season, and 2023-24 records come out right (Celtics 64-18, Nuggets 57-25, Pistons 14-68). Known cases: among players with 1,000+ minutes Jokić has the league\'s biggest on − off in 2022-23 (+26.9, interval +18.5 to +35.5), 2023-24 (+22.1) and 2024-25 (+23.3), and the Nuggets were a net negative without him in every season from 2021-22 on; Wembanyama leads 2025-26 (+18.7). Of players with 500+ minutes, 11-15% a season have an interval clear of zero, against 5% by chance. Checked on 2026-09-28.',
                limits: [
                    'Descriptive on/off, not RAPM: a player is credited with everything his lineups did, including who he played with and against, and off-court numbers depend on his backups and on when he sat (bench units, garbage time).',
                    'Ratings run about 3 points under NBA.com\'s because this possession estimate counts about 3% more possessions than the NBA\'s; on − off differences don\'t depend on the scale.',
                    'Games a player missed entirely are not off-court minutes (a different roster played them); With/Without a Star covers those. 26 player-games where the tracked on-court total exceeded the team\'s were clipped to zero off-court.',
                    'Off-court samples are thin for players who rarely sit; the interval is wide then, and the row is flagged under 300 off-court minutes.',
                ],
            },
            {
                id: 'luck',
                name: 'Luck & Schedule',
                open: { page: 'analytics', hash: 'luck', label: 'Luck & Schedule' },
                answers: 'Which teams won more (or fewer) games than their points said, how hard was their schedule, and does luck carry into the next season?',
                method: 'Every regular-season game 2009-10 to 2025-26 (20,348) with its real final score from ESPN\'s scoreboard, matched to NBA game ids (the NBA Cup final, which doesn\'t count in the standings, is left out). Expected wins: Pythagorean win% from points for and against, exponent fitted on all 510 team-seasons (13.94); it beat a normal curve and a straight line in margin per game on leave-one-season-out error (3.06 wins against 3.15 and 3.25). Luck = actual minus expected wins. Close games by final margin (3 or fewer, 5 or fewer), plus overtime records. SRS: least-squares ratings per season, each game\'s margin = home court + rating − opponent rating, ratings summing to zero; neutral-site games (international games, NBA Cup semifinals, the 2020 Orlando restart) get no home court. SOS = the average rating of the opponents actually played. The as-of view refits on the games before a date, shrinks the ratings toward average by the share of their spread that is still noise (1 − (game SD² / games) / variance), and turns each remaining game into a win chance with that season\'s home court and game SD.',
                checked: 'Season points for and against equal Basketball-Reference\'s for all 510 team-seasons, records match all 510, and our SRS matches Basketball-Reference\'s published SRS (correlation 1.000, average gap 0.01, largest 0.26 in the 2019-20 restart season): 2015-16 Warriors +10.38 and Spurs +10.28, 2016-17 Warriors +11.35, 2023-24 Celtics +10.74, 2024-25 Thunder +12.68, each first in its season. Home court fell to +0.9 points in the mostly fan-less 2020-21 season (2.1-3.2 in 2009-10 to 2019-20). Luckiest: 2022-23 Bucks (58-24, expected 49.9) and 2015-16 Warriors (73-9, expected 65.4); unluckiest: 2017-18 Mavericks and 2025-26 Hornets (−8.8), 2021-22 Celtics (51-31, expected 58.9). Luck mostly doesn\'t carry over: a franchise\'s luck correlates 0.14 with the next season\'s (95% interval 0.05 to 0.22, 480 pairs) against 0.59 for margin; close-game win% 0.11 (0.01 to 0.21). At each season\'s halfway date, ratings plus the schedule left predict rest-of-season wins within 4.5 (root-mean-square) against 4.7 for points so far and 5.0 for the record so far. Checked on 2026-09-28.',
                limits: [
                    'The small part of luck that does repeat is clear of zero, so it is not pure chance; it may be late-game execution or teams whose points the curve reads badly (starters rested early in blowouts). Next season\'s win% correlates about the same with this season\'s record (0.600) as with its expected win% (0.605).',
                    'Close-game records are small samples (about 12 games a season decided by 3 or fewer) and use the final margin, so an overtime game counts by its final score.',
                    'SRS weighs every game the same: blowouts, garbage time and games stars sat out all count at full margin, and a team that changed mid-season (trades, injuries) gets one number.',
                    'The as-of projection treats ratings as fixed for the rest of the season, so its ranges are too narrow for teams that change; every season on file is complete, so it is shown against what actually happened.',
                ],
            },
            {
                id: 'scouting',
                name: 'Scouting Report',
                open: { page: 'compare', label: 'Player Comparison' },
                answers: 'Where is a player significantly better or worse than the league?',
                method: 'Shot-zone FG% and play-type points per possession tested against the rest of the league that season, and high-leverage shooting against the player\'s own, at p < 0.05. Qualified: 1,500+ minutes.',
                checked: 'The card always shows how many splits would clear the bar by chance (about 1 in 20 tested).',
                limits: ['No pick-and-roll coverage or drive-direction data exists here; shot-context splits cover threes only.'],
            },
            {
                id: 'stability',
                name: 'Stat Stability',
                open: { page: 'stability', label: 'Stat Stability' },
                answers: 'How big a sample does each stat need before a player\'s number is more his own than luck?',
                method: 'Split-half reliability: each player-season\'s games split into odd and even games, both halves cut at the same sample (attempts, games, possessions...), centred on their season, and correlated across players. Spearman-Brown gives reliability = n / (n + M); M, the sample where it reaches 0.5, is fitted over every sample size with 100+ player-seasons, with a bootstrap 95% range. Data: play-by-play for every regular-season game 2020-21 to 2025-26 rebuilt into player lines, plus every shot since 1996-97 for FG%, 3P% and eFG%. Year-to-year correlation for every stat alongside.',
                checked: 'The rebuilt player lines match NBA.com season totals within 1.5% (minutes within 0.3% on average), and rebuilt usage, assist, rebound and turnover % correlate 0.99+ with NBA.com\'s (on-court ratings 0.96-0.99). 3P% needs 476 attempts (95% range 420-531), between the published 242 (Medvedovsky, 2020) and 750 (Blackport, 2014); free-throw % needs 27 attempts and rebound % 51 rebound chances, the fast stabilisers they are known to be; net rating needs about 1,000 possessions, in line with Medvedovsky\'s "over 1,000" for plus-minus. Checked 2026-09-28.',
                limits: [
                    'M drifts with sample size for some stats (FG% 80 to 207 attempts): the pool at big samples is only high-volume players, who are more alike. The page shows the range.',
                    'Estimated on 2020-21 to 2025-26 (shots: 1996-97 on); applying it to other eras assumes a similar spread of players.',
                    'Per-game stats settle in a game or two because minutes and role barely change; the per-minute view measures the skill. On-court ratings mostly reflect teammates.',
                    'BPM, VORP and impact score exist only as season totals, so they get only year-to-year correlation, which also counts real change (age, role, team).',
                ],
            },
            {
                id: 'aging',
                name: 'Aging Curves',
                open: { page: 'aging', label: 'Aging Curves' },
                answers: 'How does a typical player\'s game change from one age to the next, and at what age does each part of it peak?',
                method: 'Delta method: every player with two consecutive seasons of 250+ minutes (shooting % also need 100 FGA, 50 3PA or 50 FTA in both) gives one change from age a to a+1. Each season is measured against that season\'s league average first, so league-wide trends (three-point volume) don\'t count as aging. Changes are weighted by the harmonic mean of the two seasons\' minutes (attempts for shooting %), averaged per age, chained into a curve and anchored at the average 27-year-old. Ages with under 30 pairs are left off; under 100 is flagged. 95% ranges from 300 bootstrap resamples of whole careers. 24 stats (per 36 minutes, shooting, rates, BPM), each for every season it\'s recorded, the three-point era (1979-80 on) and 2009-10 on.',
                checked: 'Checked 2026-09-28: points per 36 peak at 26 (95% range 25-26) and BPM at 25 (25-26), from 16,018 and 14,167 pairs; assists (28), free-throw % (28) and three-point attempts (29) peak later, while blocks and offensive rebounds (19), rebounds (22) and steals (24) peak earlier, the athletic-first, skill-later pattern the plan expected. By 34 the typical player is 2.7 BPM below his 27-year-old self. The three eras put the peak within a year of each other for 19 of 24 stats; the other five (rebounds, rebound %, offensive rebound %, free-throw %, turnovers) differ by two years, the 2009-10-on curve being the odd one out.',
                limits: [
                    'Survivor bias: players who decline sharply often leave, so their drop never appears as a pair (at 34, 34% of qualified players never had another 250-minute season, and they were already 2.1 BPM below those who did). Declines at older ages are if anything too gentle.',
                    'Age is the age on February 1 of the season, from birth dates, in every season: the stored ages switch from Basketball-Reference\'s to NBA.com\'s (often a year older) in 2009-10, so they aren\'t used. 7 player-seasons without a birth date are left out.',
                    'Rebound %, offensive rebound %, turnover %, usage % and assist % change definition in 2009-10 (Basketball-Reference, then NBA.com), so changes across that line are left out for them.',
                    'Per 36 minutes describes the minutes a player earns, and coaches cut minutes for older players; the curve says what the typical player did, not what any one player will do.',
                ],
            },
        ],
    },
];

// Problems found and not yet fixed. Remove an entry in the commit that fixes it.
export const OPEN_ISSUES = [
    {
        title: 'A few players a season are listed under the wrong team',
        body: 'From 2020-21 on, 3 to 5 player-seasons a year in player_season_stats carry a team the player never played for that season (2024-25: Desmond Bane under ORL, Cole Anthony and Kentavious Caldwell-Pope under MEM, a later team). The team page and its payroll use the play-by-play\'s per-game teams instead and list who was left out; other tools that show a player\'s team (Player Stats, Role Player Finder, leaderboards) still show the listed one.',
    },
    {
        title: 'The Game Log overcounts minutes in 9 player-games',
        body: 'In 9 ESPN games (2020-21 to 2023-24) one substitution is logged with no team, and the per-game player lines count that player twice for the rest of the period (Luka Dončić shows 45.4 minutes on 2022-01-30; he played 37.1). The Rotations page reads the five-man stints, which only track the two real teams, so its minutes are right there and differ from the Game Log in exactly those 9 player-games. Fixing the lines means rebuilding them and everything built on them (on/off, Stat Stability, Hot Streaks, Situational Splits, Projections), so it is planned as one deliberate rebuild.',
    },
    {
        title: 'Some models can\'t be retrained right now',
        body: 'stats.nba.com has been unreachable from the build machine since 2026-09-26, so Pair Synergy still uses the old in-house defensive BPM it was trained on.',
    },
];
