// Content for the Methodology page. Every number here was checked against
// the live endpoint or the build script's own output on the date given;
// the award models and the win-probability model are fetched live instead.
// When a model changes, change its entry in the same commit.

export const CHECKED_ON = '2026-09-27';

export const PRINCIPLES = [
    ['Real data only', 'Every number comes from a stored table or a live source; nothing is filled in with placeholders.'],
    ['Held-out checks', 'Predictive models are scored on seasons or games they never trained on.'],
    ['Null results stay in', 'When a model finds nothing (College → NBA Pipeline) or doesn\'t beat a simple baseline (March Madness champions), the page says so.'],
    ['Samples are shown', 'Small samples are flagged or greyed out rather than ranked beside reliable ones.'],
    ['Association is not cause', 'Descriptive studies say what went together, not why.'],
];

// kind: 'model' (predicts), 'index' (a rating built from a formula),
// 'similarity', 'study' (describes what happened).
export const SECTIONS = [
    {
        id: 'predictive',
        title: 'Predictive models',
        blurb: 'Models that output a probability. Each is scored on data it never saw.',
        items: [
            {
                id: 'awards',
                name: 'Award models (MVP, DPOY, ROY, All-NBA)',
                open: { page: 'analytics', hash: 'mvp', label: 'Awards Race' },
                answers: 'Who is on course to win each award this season?',
                method: 'One logistic regression per award on season stats, standardised; random forest and gradient boosting are backtested alongside for comparison. The models are trained with balanced class weights, so their raw outputs run far too high (several players at 99%+ at once). The app shows a calibrated chance instead: for MVP, DPOY and ROY the scores are turned into chances that add up to 100% across the field; for All-NBA (15 selections) they are Platt-scaled to add up to about 15.',
                checked: 'Leave-one-season-out: each past season is predicted by a model trained without it, then compared with the real winner (live table below; Model Validation has the ROC curves). The calibration is fitted on those held-out scores and checked in a nested loop, so no season is scored by a calibration that saw it (live table below).',
                limits: [
                    'The calibration rests on 14 to 16 seasons, so the percentages are approximate; the MVP favourite averaged a 55% chance and won 7 of 15.',
                    'The Prediction Ledger keeps the raw probabilities that were logged before 2026-09-27.',
                    'Voter narrative and the league\'s 65-game eligibility rule are not modelled; DPOY and All-NBA only apply a minutes floor to who counts as a candidate.',
                    'ROY candidates are players in their first NBA season per Basketball-Reference. Until 2026-09-27 the first season in this database was used, which let in 240 players with missing earlier stints (53 in 2025-26); the ROY model was retrained on the corrected pool.',
                ],
                live: 'awards',
            },
            {
                id: 'wp',
                name: 'Win probability (Clutch WPA, Game Replay, Garbage-Time, Guess the Game)',
                open: { page: 'analytics', hash: 'wpa', label: 'Clutch WPA' },
                answers: 'Given the score margin and the time left, how likely is the home team to win?',
                method: 'Logistic regression with isotonic calibration on three inputs (seconds left, home score margin, and margin divided by the square root of time left), trained on play-by-play from 7,232 games (2020-21 to 2025-26). WPA per play = win probability after it minus before it, credited to the player who made it.',
                checked: 'Held out by game, not by play, so a game\'s later plays can\'t leak into training. Brier score, log loss and a reliability curve on the held-out games (live numbers below).',
                limits: [
                    'Possession, timeouts and fouls to give are not inputs, so in a close finish the model can\'t tell who has the ball.',
                    'Covers 2020-21 onward only (the play-by-play on file).',
                    '1.4% of play-by-play events couldn\'t be matched to a player id by name and carry no player credit.',
                    'Clutch-time predictions sit near 50/50, so their scores aren\'t directly comparable with the all-events scores.',
                ],
                live: 'wp',
            },
            {
                id: 'madness',
                name: 'March Madness model',
                open: { page: 'analytics', hash: 'madness', label: 'March Madness' },
                answers: 'Pre-tournament odds for every team in the NCAA bracket.',
                method: 'Opponent- and venue-adjusted scoring margin (ridge least squares on every D1 game before the tournament), logistic regression on the difference between two teams, 20,000 simulations of the real bracket.',
                checked: 'Five input sets compared by leave-one-season-out log loss on 2013-2025 (801 games); adjusted margin alone won (0.557). 2026 was held back entirely and run once: Michigan won; the model had them 3rd (18.9%).',
                limits: [
                    'Better calibrated than seeds game by game, but not better at finding the champion: the champion was its favourite in 2 of 12 backtest seasons, and a 1 seed in 9.',
                    'Torvik\'s end-of-season ratings are never used as inputs: they include the tournament.',
                ],
            },
        ],
    },
    {
        id: 'indexes',
        title: 'Ratings and indexes',
        blurb: 'Formulas that turn data into one number. Each says what it leaves out.',
        items: [
            {
                id: 'bpm',
                name: 'BPM and VORP',
                open: { page: 'analytics', hash: 'impact', label: 'Impact Rankings' },
                answers: 'How much a player adds per 100 possessions (BPM), and in total over a replacement player (VORP).',
                method: 'Basketball-Reference\'s published values, loaded for every season; 2009-10 onward is linked to NBA ids through the project\'s id map (7,273 of 7,279 rows; the 6 unlinked are left empty).',
                checked: 'Games played agree within one game on every linked row, an independent check of the id link.',
                limits: [
                    'Until 2026-09-27 the app used its own BPM reproduction, which ran hot (2025-26 SGA at 22.0 vs the published 11.7). It is kept only as an input to Pair Synergy, whose trained model was fitted on it.',
                    'Box-score based: defence away from the ball is only partly captured.',
                ],
            },
            {
                id: 'dad',
                name: 'DAD Index (Defensive Assignment Difficulty)',
                open: { page: 'analytics', hash: 'dad', label: 'DAD Index' },
                answers: 'How hard were the players each defender actually guarded?',
                method: 'Share of the defender\'s tracked possessions against each opponent × that opponent\'s offensive BPM (Basketball-Reference). Opponents under 500 minutes count as replacement level (−2.0). Z-scored per season, with a within-position version.',
                checked: 'Year-over-year stability r = 0.70 for 243 defenders qualified in both 2024-25 and 2025-26.',
                limits: [
                    'Describes assignments, not a full defensive rating: no help defence, rebounding or scheme.',
                    'Matchup pairs under 5 partial possessions were dropped when the data was fetched.',
                    'Qualified defenders only (1,000+ partial possessions).',
                ],
            },
            {
                id: 'gravity',
                name: 'Gravity Index and Spacing Lab',
                open: { page: 'analytics', hash: 'spacing', label: 'Spacing Lab' },
                answers: 'How much does a shooter pull the defence, and do well-spaced lineups score more?',
                method: 'A proxy, not tracking gravity: 3PA per 100 possessions, catch-and-shoot 3P% and the share of threes taken with a defender within 6 ft, each z-scored within the season (500+ minutes) and summed. Lineup spacing = the five players\' sum.',
                checked: 'Offensive rating of 4,250 lineups (100+ possessions, 2013-14 to 2025-26) regressed on spacing plus the five players\' summed OBPM, season fixed effects, errors clustered by team-season: +0.074 ORtg per spacing point (95% CI 0.014 to 0.134, p = 0.016).',
                limits: [
                    'The effect is small: spacing adds 0.001 to R² once lineup quality is in the model.',
                    'An association across lineups, not a forecast for a specific five.',
                ],
            },
            {
                id: 'contracts',
                name: 'Contract Value',
                open: { page: 'analytics', hash: 'contracts', label: 'Contract Value' },
                answers: 'Is a player worth their salary?',
                method: 'WAR = published VORP × 2.7, rescaled per season so positive WAR adds up to the league\'s real wins above replacement (factor 0.77 to 0.80). Fair value = WAR × that season\'s cost per win + the league minimum.',
                checked: 'Cost per win is built from real salaries, real team records and the real minimum salary for each season: $2.08M per win in 2005-06 up to $6.11M in 2024-25.',
                limits: [
                    'Salary data is third-party (Kaggle uploads built from HoopsHype and Basketball-Reference) and imperfect.',
                    'Covers 2005-06 to 2016-17, 2018-19, 2019-20 and 2024-25 only.',
                    'Only players who played are priced.',
                ],
            },
            {
                id: 'tradeimpact',
                name: 'Trade Impact',
                open: { page: 'tradeimpact', label: 'Trade Impact' },
                answers: 'For a 1-for-1 trade, what happens to each team\'s projected wins, starting-five spacing, payroll and surplus?',
                method: 'Nothing new is estimated. Projected win% is the Trade Analyzer\'s regression on the roster\'s minute-weighted net rating and TS% (players keep their own season stats). Spacing is the Gravity Index summed over the team\'s most-used real five-man lineup, with the incoming player in the outgoing player\'s spot (or the lowest-minute starter\'s spot if the outgoing player wasn\'t in that five). Payroll and surplus are Contract Value\'s, summed over the players with matched salaries who played for the team.',
                checked: 'Each piece carries its own validation (see the Gravity and Contract Value cards; the win model is leave-one-season-out R² 0.92, about 2.5 wins of error over 82 games). Checked on a real 2024-25 case: the Knicks\' most-used five is their real starting five (1,939 possessions), and swapping Josh Hart for Duncan Robinson moves its spacing from the 81st to the 97th percentile while payroll changes by the real $1.26M salary difference.',
                limits: [
                    'Role, usage and minutes changes after a trade are not simulated; the win change is a roster-production estimate.',
                    'Spacing is a proxy with a small validated effect on offensive rating; the starting five after the trade is an assumption stated on the page.',
                    'Payroll is the priced on-court payroll, not the cap sheet, and only for seasons with reliable salary data (2005-06 to 2016-17, 2018-19, 2019-20, 2024-25). 2024-25 is the only season with all three blocks after 2019-20.',
                    'One-for-one trades only.',
                ],
            },
            {
                id: 'rolefinder',
                name: 'Role Player Finder',
                open: { page: 'rolefinder', label: 'Role Player Finder' },
                answers: 'Which players best fit a role such as 3-and-D wing or rim protector?',
                method: 'Score = the sum of weight × z-score over a role\'s components, within one season among players with 500+ minutes (2017-18 on, when every input exists). DAD and Gravity components use those tables\' stored z-scores; blocks and steals per 36, rebound, assist, usage and turnover rates, true shooting, BPM parts and the defended-FG% differential are z-scored here. "Compare with the chosen positions" re-scores everything within the selected positions. Scouting Report findings are shown as fit flags, not scored.',
                checked: 'The presets\' weights are a judgment call, written down and shown in full on the page, not fitted to anything. Sniff tests on 2024-25: rim protector puts Wembanyama, Holmgren and Kessler 1-2-3; point-of-attack puts Caruso, Ausar Thompson and Dyson Daniels 1-2-3; floor spacer starts Beasley, Isaiah Joe, Curry; 3-and-D starts Dort, Finney-Smith, Caruso, with Anunoby 2nd in 2025-26.',
                limits: [
                    'Known misses: Rudy Gobert ranks about 20th as a rim protector because his deterrence shows up as few blocks and a modest defended-FG% effect; Brook Lopez sits mid-pack as a stretch big on 2024-25 volume.',
                    'A player missing a weighted component (under 1,000 tracked defensive possessions, or under 2 three-point attempts a game for 3P%) is left out, not treated as average; the page counts them.',
                    'Salary filtering only exists for the seasons with contract data (2017-18 to 2019-20 and 2024-25).',
                ],
            },
            {
                id: 'garbage',
                name: 'Garbage-Time Deflator',
                open: { page: 'analytics', hash: 'garbage', label: 'Garbage-Time Deflator' },
                answers: 'How much of a player\'s scoring came when the game was already decided?',
                method: 'Every play gets a leverage index from the win-probability model (average play = 1.0). Garbage time = win probability above 99% either way, or a margin of 18+ in the second half or overtime.',
                checked: 'Buckets are applied in a fixed order and their shares are shown; the "stat-padding" badge is only given at the 90th percentile or above among 40+ game players.',
                limits: [
                    'ESPN play-by-play only, 2020-21 to 2025-26.',
                    'Thresholds are choices, stated on the page, not facts.',
                ],
            },
            {
                id: 'helio',
                name: 'Heliocentricity Index',
                open: { page: 'analytics', hash: 'helio', label: 'Heliocentricity' },
                answers: 'Whose team\'s offence runs through them most?',
                method: 'The average of four percentile ranks within the season: time-of-possession share, touches, usage and assist percentage.',
                checked: 'Descriptive only; the weights are equal on purpose and disclosed.',
                limits: ['Not predictive and not a measure of value: a high score can be good or bad for a team.'],
            },
            {
                id: 'era',
                name: 'Era Translator',
                open: { page: 'era', label: 'Era Translator' },
                answers: 'What would a season from one era look like in another season\'s game?',
                method: 'Two restatements. Pace only: each per-game count × (target league pace ÷ source league pace), percentages unchanged. Pace + league: each count × (target ÷ source league average per team game for that stat), so the player keeps the same share of an average team\'s output; percentages move by the change in league average; threes stay pace-only. Beside them, the era-free view: z-score and percentile within the player\'s own season. League averages are Basketball-Reference\'s.',
                checked: 'Checked 2026-09-28: Oscar Robertson 1961-62 (30.8 / 12.5 / 11.4) restates to 24.3 / 9.8 / 9.0 at 2025-26\'s pace, against 24.5 / 9.9 / 9.1 from Neil Paine\'s published per-100-possession line at the same pace and minutes; Wilt\'s 50.4 points becomes 39.7.',
                limits: [
                    'Pace before 1973-74 is an estimate (offensive rebounds and turnovers weren\'t recorded); 1949-50 is estimated by this app.',
                    'League pace, not the team\'s: Wilt\'s 1961-62 Warriors played faster than the league, so his restated line is about 4% too high.',
                    'The two answers differ a lot for points (39.7 vs 49.0 for Wilt): neither says how a player would have adapted to another era\'s rules, spacing or athletes.',
                ],
            },
        ],
    },
    {
        id: 'similarity',
        title: 'Similarity and clustering',
        blurb: 'Grouping and matching players. Every stat is compared within its own season first, so eras compare fairly.',
        items: [
            {
                id: 'similarity',
                name: 'Season Similarity',
                open: { page: 'analytics', hash: 'similarity', label: 'Season Similarity' },
                answers: 'Which player-seasons look most like this one?',
                method: 'Eight numbers per season (points, true shooting, usage, net rating, assist %, rebound % z-scored within the season, plus age and minutes), standardised, compared by cosine similarity.',
                checked: 'The live view was checked against the stored top 10 for all 7,279 seasons: identical scores and lists. A smoke test re-checks one season on every run.',
                limits: [
                    '2009-10 onward only: usage and net rating aren\'t on file before that.',
                    'Cosine compares shape, so a smaller version of the same profile can still score high; the stat line is shown next to each match for that reason.',
                ],
            },
            {
                id: 'statline',
                name: 'Stat Line Finder',
                open: { page: 'statline', label: 'Stat Line Finder' },
                answers: 'Which real player-seasons are closest to a stat line I type?',
                method: 'Each stat (points, rebounds, assists, steals, blocks, turnovers, 3PA, 3P%, FT%, TS%, usage, assist %, rebound %, net rating, minutes, age) is z-scored within its own season over every player-season that has it; shooting percentages only over players above the Leaderboard Builder\'s attempts floor. The typed line is z-scored against the season the user picks, and every player-season is ranked by the root-mean-square gap in z-scores over the typed stats only (0 = the same standing on every stat). Levels are matched, not the shape of the profile as in Season Similarity.',
                checked: 'Typing a real season\'s own line in its own season returns that season first at distance 0 (Curry 2015-16, LeBron James 2012-13, Wilt Chamberlain 1961-62; checked 2026-09-28, and a smoke test re-checks Curry and Wilt on every run). 3 blocks and 12 rebounds today returns Olajuwon 1992-93, Camby, Mutombo, Wembanyama and Robinson.',
                limits: [
                    'Standing is era-relative, so a match from another era can show raw numbers unlike the typed ones (60% TS today matches 52% TS in 1975-76, when the league shot worse).',
                    'Each stat counts equally; there are no weights. A stat is only usable from its first well-recorded season (steals and blocks 1973-74, threes 1979-80, net rating 2009-10).',
                    'A line far outside anything real (Wilt\'s 50 and 26 read in 2025-26) still returns the nearest seasons; the page warns when the best match is more than one standard deviation away.',
                ],
            },
            {
                id: 'roles',
                name: 'Player Roles',
                open: { page: 'analytics', hash: 'archetypes', label: 'Player Archetypes' },
                answers: 'What kind of player is this, judged by what they do with their minutes?',
                method: 'K-Means on rate stats and shot-location shares, z-scored within each season: 5,386 player-seasons 2010-2026 (15+ minutes, 20+ games, 100+ located shots).',
                checked: 'Ten roles is the most whose grouping survives refitting on 80% subsamples (adjusted Rand 0.83; 11 or more drop to 0.52-0.64).',
                limits: ['Separation is low at every K (silhouette 0.10): playing styles are a continuum, and many players sit between two roles.'],
            },
            {
                id: 'offstyle',
                name: 'Offensive Style',
                open: { page: 'analytics', hash: 'archetypes', label: 'Player Archetypes' },
                answers: 'How does a player\'s offence get generated?',
                method: 'K-Means on play-type shares (isolation, pick-and-roll, spot-up, post-up, transition, roll man), era-normalised.',
                checked: 'Silhouette 0.21, disclosed as weaker separation than the stat-based groups.',
                limits: ['Play-type mixes overlap a lot; treat the style as a tendency.'],
            },
            {
                id: 'prospects',
                name: 'Draft Prospect Comp Finder',
                open: { page: 'analytics', hash: 'prospects', label: 'Draft Prospects' },
                answers: 'Which past college players does a prospect resemble, and how did they do in the NBA?',
                method: 'Around 105,000 D1 player-seasons, era-normalised, matched by similarity; optional combine measurements.',
                checked: 'NBA outcomes shown only where a real name match exists.',
                limits: ['About 55% of NBA rookies since 2015 have a US college record; international and G League players never appear.'],
            },
        ],
    },
    {
        id: 'studies',
        title: 'Descriptive studies',
        blurb: 'What happened, measured carefully. None of these claims a cause.',
        items: [
            {
                id: 'clutch',
                name: 'Clutch vs. non-clutch',
                open: { page: 'analytics', hash: 'wpa', label: 'Clutch WPA' },
                answers: 'Does a player do better or worse in clutch time than in the rest of the game?',
                method: 'Each play\'s WPA divided by its leverage (the win-probability value of one point at that moment, from the win-probability model), summed over a player\'s shots, free throws and turnovers: WPA per scoring chance, in points, at equal leverage. Clutch lift = clutch rate − non-clutch rate − the league\'s own change (0.843 vs 0.914), with a 95% interval clustered by game.',
                checked: 'The unit reads as points: the league\'s 0.914 per chance outside clutch time sits inside its real points per (FGA + FTA + TOV), 0.90-0.93 in 2020-21 to 2025-26. With 100+ clutch chances, 14 of 186 players land outside zero at 95%, where about 9 would by chance; lift divided by its standard error has an SD of 1.09 (1.0 would be pure noise). Checked 2026-09-28.',
                limits: [
                    'Clutch plays swing win probability 3.7 times as much as an average play, so raw clutch WPA mostly counts how many clutch plays a player got; the lift removes that.',
                    'The model doesn\'t know who has the ball, so a miss or turnover costs nothing: this measures scoring, not defense or decisions.',
                    'Pooled over 2020-21 to 2025-26, not per season.',
                    'About 1 in 20 players clears the 95% bar by chance, so one "better" or "worse" verdict is weak evidence.',
                ],
            },
            {
                id: 'pipeline',
                name: 'College → NBA Pipeline',
                open: { page: 'analytics', hash: 'pipeline', label: 'College Pipeline' },
                answers: 'Do players from stronger college teams outperform their draft slot?',
                method: 'Win Shares in the first four NBA seasons compared with a draft-slot expectation fitted on 598 picks (2013-2022).',
                checked: 'Bootstrap intervals on every group; 478 college players from classes old enough to judge.',
                limits: ['A null result: +0.38 Win Shares per 10 points of team margin (95% range −0.30 to +1.04, r = 0.05). Once you know the pick, college team strength barely matters.'],
            },
            {
                id: 'draft',
                name: 'Draft Value',
                open: { page: 'draft', label: 'Draft Value Guide' },
                answers: 'What is a draft slot usually worth?',
                method: 'Basketball-Reference Win Shares in each pick\'s first five NBA seasons, draft classes 1980-2021.',
                checked: 'Slot averages 23.6 / 14.4 / 8.4 / 3.9 / 1.9 Win Shares for picks 1-5 / 6-14 / 15-30 / 31-45 / 46-60; career totals spot-checked against Basketball-Reference.',
                limits: ['Win Shares lean on team results, especially on defence; five seasons misses late bloomers.'],
            },
            {
                id: 'referees',
                name: 'Referee Tendencies',
                open: { page: 'analytics', hash: 'referees', label: 'Referee Tendencies' },
                answers: 'Do games an official works produce more fouls, free throws or pace than usual?',
                method: 'Each official\'s games compared with the league average for the same seasons, with a 95% confidence interval on the difference.',
                checked: 'Officials with under 25 games are flagged as a small sample, not ranked.',
                limits: ['Crew assignment, opponents and era are unmeasured; coverage grows as the resumable fetch is re-run.'],
            },
            {
                id: 'matchups',
                name: 'Matchup Finder',
                open: { page: 'analytics', hash: 'matchups', label: 'Matchup Finder' },
                answers: 'Which defenders hold a scorer down, and who torches whom?',
                method: 'NBA player-vs-player matchup tracking, 2017-18 to 2025-26 (571,608 rows).',
                checked: 'Pairs under 20 partial possessions are greyed out and marked small sample.',
                limits: ['One defended shot is 0% or 100%: small pairs are noise even when shown.'],
            },
            {
                id: 'lineups',
                name: 'Lineup Chemistry and With vs. Without',
                open: { page: 'analytics', hash: 'lineups', label: 'Lineup Chemistry' },
                answers: 'How did real five-man units, and teams with and without a star, actually do?',
                method: 'Real lineup ratings with a stated minutes cutoff; team results split by whether a player played.',
                checked: 'The 2023-24 76ers with and without Embiid (79.5% vs 37.2% wins) reproduce that season\'s known story.',
                limits: ['Other absences and opponents aren\'t controlled for; small lineups are noisy.'],
            },
            {
                id: 'pairs',
                name: 'Pair Chemistry',
                open: { page: 'analytics', hash: 'pairs', label: 'Pair Chemistry' },
                answers: 'How did a team do with each pair of its players on the floor together?',
                method: 'Every stored five-man lineup containing both players, summed: minutes and possessions added up, offensive and defensive ratings weighted by possessions. Colours compare each pair with the team over the same lineups; pairs under a shared-minutes floor (default 100) are greyed out.',
                checked: 'The 2015-16 Warriors: Curry and Green are the most-shared pair (2,179 stored minutes, +19.8) and the top three pairs with 500+ shared minutes all include Iguodala; no player\'s stored minutes exceed their season minutes. Checked on 2026-09-28.',
                limits: ['Only the league\'s 2,000 most-used lineups a season are stored: 31-89% of a team\'s minutes (median 65%), with bench units missing most, so a team\'s figure over these lineups runs above its real net rating.', 'Descriptive: not adjusted for opponents or for the other three players on the floor.'],
            },
            {
                id: 'scouting',
                name: 'Scouting Report',
                open: { page: 'compare', label: 'Player Comparison' },
                answers: 'Where is a player significantly better or worse than the league?',
                method: 'Shot-zone FG% and play-type points per possession tested against the rest of the league that season, and high-leverage shooting against the player\'s own, at p < 0.05. Qualified: 1,500+ minutes.',
                checked: 'The card always shows how many splits would clear the bar by chance (about 1 in 20 tested).',
                limits: ['No pick-and-roll coverage or drive-direction data exists here; shot-context splits cover threes only.'],
            },
            {
                id: 'stability',
                name: 'Stat Stability',
                open: { page: 'stability', label: 'Stat Stability' },
                answers: 'How big a sample does each stat need before a player\'s number is more his own than luck?',
                method: 'Split-half reliability: each player-season\'s games split into odd and even games, both halves cut at the same sample (attempts, games, possessions...), centred on their season, and correlated across players. Spearman-Brown gives reliability = n / (n + M); M, the sample where it reaches 0.5, is fitted over every sample size with 100+ player-seasons, with a bootstrap 95% range. Data: play-by-play for every regular-season game 2020-21 to 2025-26 rebuilt into player lines, plus every shot since 1996-97 for FG%, 3P% and eFG%. Year-to-year correlation for every stat alongside.',
                checked: 'The rebuilt player lines match NBA.com season totals within 1.5% (minutes within 0.3% on average), and rebuilt usage, assist, rebound and turnover % correlate 0.99+ with NBA.com\'s (on-court ratings 0.96-0.99). 3P% needs 476 attempts (95% range 420-531), between the published 242 (Medvedovsky, 2020) and 750 (Blackport, 2014); free-throw % needs 27 attempts and rebound % 51 rebound chances, the fast stabilisers they are known to be; net rating needs about 1,000 possessions, in line with Medvedovsky\'s "over 1,000" for plus-minus. Checked 2026-09-28.',
                limits: [
                    'M drifts with sample size for some stats (FG% 80 to 207 attempts): the pool at big samples is only high-volume players, who are more alike. The page shows the range.',
                    'Estimated on 2020-21 to 2025-26 (shots: 1996-97 on); applying it to other eras assumes a similar spread of players.',
                    'Per-game stats settle in a game or two because minutes and role barely change; the per-minute view measures the skill. On-court ratings mostly reflect teammates.',
                    'BPM, VORP and impact score exist only as season totals, so they get only year-to-year correlation, which also counts real change (age, role, team).',
                ],
            },
        ],
    },
];

// Problems found and not yet fixed. Remove an entry in the commit that fixes it.
export const OPEN_ISSUES = [
    {
        title: 'Some models can\'t be retrained right now',
        body: 'stats.nba.com has been unreachable from the build machine since 2026-09-26, so Pair Synergy still uses the old in-house defensive BPM it was trained on.',
    },
];
